name: "🐛 Bug Report"
description: Create a report to help us improve Plausible Analytics
body:
  - type: markdown
    attributes:
     value: |
       Thanks for taking the time to fill out this bug report!

       Please note that this tracker is only for bugs. Do not use the issue tracker for help, customer support or feature requests.

       [Our docs](https://plausible.io/docs) are a great place for most answers, but if you can’t find your answer there, you can [contact our customer support](https://plausible.io/contact).

       Have a feature request? Please search the ideas [on our forum](https://github.com/plausible/analytics/discussions/categories/feature-requests) to make sure that the feature has not yet been requested. If you cannot find what you had in mind, please [submit your feature request here](https://github.com/plausible/analytics/discussions/new).

       Have an issue with your self-hosted install? Self-hosted is community supported and you can ask in [our self-hosted forum](https://github.com/plausible/analytics/discussions/categories/self-hosted-support).

       Note that self-hosted is a long term release published twice per year so latest features won’t be immediately available. You can see all the [currently unreleased features in the changelog](https://github.com/plausible/analytics/blob/master/CHANGELOG.md).

       **Thanks!**
  - type: checkboxes
    attributes:
      label: Past Issues Searched
      options:
        - label: >-
            I have searched open and closed issues to make sure that the bug has
            not yet been reported
          required: true
  - type: checkboxes
    attributes:
      label: Issue is a Bug Report
      options:
        - label: >-
            This is a bug report and not a feature request, nor asking for self-hosted support
          required: true
  - type: dropdown
    id: version
    attributes:
      label: Using official Plausible Cloud hosting or self-hosting?
      options:
        - Plausible Cloud from plausible.io
        - Self-hosting
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened!
    validations:
      required: true
  - type: textarea
    id: bug-expectation
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
      placeholder: Tell us what you expected
    validations:
      required: true
  - type: textarea
    id: bug-screenshots
    attributes:
      label: Screenshots
      description: 'If applicable, add screenshots to help explain your problem'
      placeholder: Insert screenshots here
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
        - **OS**: MacOS
        - **Browser**: Firefox
        - **Browser Version**: 88
      value: |
        - OS:
        - Browser:
        - Browser Version:
      render: markdown
