# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.4.1"
    hooks:
      - id: prettier
        files: "assets/js|assets/css"
        args: [--config, assets/.prettierrc.json]

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: '0.0.2'
    hooks:
    -   id: stylelint
        additional_dependencies:
          - stylelint@13.2.1
          - stylelint-config-standard@20.0.0

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.3.0'
    hooks:
      - id: eslint
        files: "assets/js|tracker/test"
        additional_dependencies:
          - eslint@7.30.0
          - eslint-plugin-import@2.22.1
          - eslint-plugin-jsx-a11y@6.4.1
          - eslint-plugin-react@7.21.5
          - eslint-plugin-react-hooks@4.2.0

  - repo: https://gitlab.com/jvenom/elixir-pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: mix-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: priv/tracker/js
      - id: mixed-line-ending
      - id: trailing-whitespace
